# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_types/Position.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class Position(genpy.Message):
  _md5sum = "ad7ebc1d669ad680b4c5c766755341b3"
  _type = "msg_types/Position"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """time stamp
float32 x
float32 y
float32 t
uint32 id
bool actual
"""
  __slots__ = ['stamp','x','y','t','id','actual']
  _slot_types = ['time','float32','float32','float32','uint32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,x,y,t,id,actual

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Position, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.t is None:
        self.t = 0.
      if self.id is None:
        self.id = 0
      if self.actual is None:
        self.actual = False
    else:
      self.stamp = genpy.Time()
      self.x = 0.
      self.y = 0.
      self.t = 0.
      self.id = 0
      self.actual = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I3fIB().pack(_x.stamp.secs, _x.stamp.nsecs, _x.x, _x.y, _x.t, _x.id, _x.actual))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 25
      (_x.stamp.secs, _x.stamp.nsecs, _x.x, _x.y, _x.t, _x.id, _x.actual,) = _get_struct_2I3fIB().unpack(str[start:end])
      self.actual = bool(self.actual)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I3fIB().pack(_x.stamp.secs, _x.stamp.nsecs, _x.x, _x.y, _x.t, _x.id, _x.actual))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 25
      (_x.stamp.secs, _x.stamp.nsecs, _x.x, _x.y, _x.t, _x.id, _x.actual,) = _get_struct_2I3fIB().unpack(str[start:end])
      self.actual = bool(self.actual)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I3fIB = None
def _get_struct_2I3fIB():
    global _struct_2I3fIB
    if _struct_2I3fIB is None:
        _struct_2I3fIB = struct.Struct("<2I3fIB")
    return _struct_2I3fIB
