// Generated by gencpp from file msg_types/ControlCmd.msg
// DO NOT EDIT!


#ifndef MSG_TYPES_MESSAGE_CONTROLCMD_H
#define MSG_TYPES_MESSAGE_CONTROLCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace msg_types
{
template <class ContainerAllocator>
struct ControlCmd_
{
  typedef ControlCmd_<ContainerAllocator> Type;

  ControlCmd_()
    : header()
    , v(0.0)
    , w(0.0)  {
    }
  ControlCmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , v(0.0)
    , w(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _v_type;
  _v_type v;

   typedef float _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::msg_types::ControlCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_types::ControlCmd_<ContainerAllocator> const> ConstPtr;

}; // struct ControlCmd_

typedef ::msg_types::ControlCmd_<std::allocator<void> > ControlCmd;

typedef boost::shared_ptr< ::msg_types::ControlCmd > ControlCmdPtr;
typedef boost::shared_ptr< ::msg_types::ControlCmd const> ControlCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_types::ControlCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_types::ControlCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_types::ControlCmd_<ContainerAllocator1> & lhs, const ::msg_types::ControlCmd_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.v == rhs.v &&
    lhs.w == rhs.w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_types::ControlCmd_<ContainerAllocator1> & lhs, const ::msg_types::ControlCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_types

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::msg_types::ControlCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_types::ControlCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_types::ControlCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_types::ControlCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_types::ControlCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_types::ControlCmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_types::ControlCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c9739f01512ce85d8ac1ccdd6bde650b";
  }

  static const char* value(const ::msg_types::ControlCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc9739f01512ce85dULL;
  static const uint64_t static_value2 = 0x8ac1ccdd6bde650bULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_types::ControlCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_types/ControlCmd";
  }

  static const char* value(const ::msg_types::ControlCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_types::ControlCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 v\n"
"float32 w\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::msg_types::ControlCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_types::ControlCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.v);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_types::ControlCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_types::ControlCmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "v: ";
    Printer<float>::stream(s, indent + "  ", v.v);
    s << indent << "w: ";
    Printer<float>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_TYPES_MESSAGE_CONTROLCMD_H
