// Generated by gencpp from file msg_types/Position.msg
// DO NOT EDIT!


#ifndef MSG_TYPES_MESSAGE_POSITION_H
#define MSG_TYPES_MESSAGE_POSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_types
{
template <class ContainerAllocator>
struct Position_
{
  typedef Position_<ContainerAllocator> Type;

  Position_()
    : stamp()
    , x(0.0)
    , y(0.0)
    , t(0.0)
    , id(0)
    , actual(false)  {
    }
  Position_(const ContainerAllocator& _alloc)
    : stamp()
    , x(0.0)
    , y(0.0)
    , t(0.0)
    , id(0)
    , actual(false)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _t_type;
  _t_type t;

   typedef uint32_t _id_type;
  _id_type id;

   typedef uint8_t _actual_type;
  _actual_type actual;





  typedef boost::shared_ptr< ::msg_types::Position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_types::Position_<ContainerAllocator> const> ConstPtr;

}; // struct Position_

typedef ::msg_types::Position_<std::allocator<void> > Position;

typedef boost::shared_ptr< ::msg_types::Position > PositionPtr;
typedef boost::shared_ptr< ::msg_types::Position const> PositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_types::Position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_types::Position_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace msg_types

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'msg_types': ['/home/cconejob/StudioProjects/Autonomous_driving_pipeline/src/msg_types/msg', '/home/cconejob/StudioProjects/Autonomous_driving_pipeline/src/msg_types/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::msg_types::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_types::Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_types::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_types::Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_types::Position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_types::Position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_types::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad7ebc1d669ad680b4c5c766755341b3";
  }

  static const char* value(const ::msg_types::Position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad7ebc1d669ad680ULL;
  static const uint64_t static_value2 = 0xb4c5c766755341b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_types::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_types/Position";
  }

  static const char* value(const ::msg_types::Position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_types::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n\
float32 x\n\
float32 y\n\
float32 t\n\
uint32 id\n\
bool actual\n\
";
  }

  static const char* value(const ::msg_types::Position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_types::Position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.t);
      stream.next(m.id);
      stream.next(m.actual);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_types::Position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_types::Position_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "t: ";
    Printer<float>::stream(s, indent + "  ", v.t);
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "actual: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.actual);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_TYPES_MESSAGE_POSITION_H
